version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - "3001:3001"
    platform: linux/x86_64
    working_dir: /frontend
    depends_on:
      - backend
    restart: always
    networks:
      - web-net
  
  backend:
    container_name: app_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    platform: linux/x86_64
    working_dir: /backend
    restart: always
    networks:
      - web-net

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5434'
    networks:
      - web-net

  init-db:
    image: node:18
    volumes:
      - ./
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5434/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: ["sh", "-c", "npm install && npm install -g nodemon"]
    depends_on:
      - backend
      - postgres
    networks:
      - web-net

volumes:
  postgres:
  data: {}
networks:
  web-net:
    name: web-net
